apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-{{ template "kube-prometheus-stack.alertmanager.crname" . }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
{{- if .Values.alertmanager.secret.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.secret.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-alertmanager
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
data:
  alertmanager.yaml: ICAgIGdsb2JhbDoKICAgICAgcmVzb2x2ZV90aW1lb3V0OiA1bQogICAgaW5oaWJpdF9ydWxlczoKICAgICAgLSBzb3VyY2VfbWF0Y2hlcnM6CiAgICAgICAgICAtICdzZXZlcml0eSA9IGNyaXRpY2FsJwogICAgICAgIHRhcmdldF9tYXRjaGVyczoKICAgICAgICAgIC0gJ3NldmVyaXR5ID1+IHdhcm5pbmd8aW5mbycKICAgICAgICBlcXVhbDoKICAgICAgICAgIC0gJ25hbWVzcGFjZScKICAgICAgICAgIC0gJ2FsZXJ0bmFtZScKICAgICAgLSBzb3VyY2VfbWF0Y2hlcnM6CiAgICAgICAgICAtICdzZXZlcml0eSA9IHdhcm5pbmcnCiAgICAgICAgdGFyZ2V0X21hdGNoZXJzOgogICAgICAgICAgLSAnc2V2ZXJpdHkgPSBpbmZvJwogICAgICAgIGVxdWFsOgogICAgICAgICAgLSAnbmFtZXNwYWNlJwogICAgICAgICAgLSAnYWxlcnRuYW1lJwogICAgICAtIHNvdXJjZV9tYXRjaGVyczoKICAgICAgICAgIC0gJ2FsZXJ0bmFtZSA9IEluZm9JbmhpYml0b3InCiAgICAgICAgdGFyZ2V0X21hdGNoZXJzOgogICAgICAgICAgLSAnc2V2ZXJpdHkgPSBpbmZvJwogICAgICAgIGVxdWFsOgogICAgICAgICAgLSAnbmFtZXNwYWNlJwogICAgcm91dGU6CiAgICAgIGdyb3VwX2J5OiBbJ25hbWVzcGFjZSddCiAgICAgIGdyb3VwX3dhaXQ6IDMwcwogICAgICBncm91cF9pbnRlcnZhbDogNW0KICAgICAgcmVwZWF0X2ludGVydmFsOiAxMmgKICAgICAgcmVjZWl2ZXI6ICdzbGFjaycKICAgICAgcm91dGVzOgogICAgICAtIHJlY2VpdmVyOiAnc2xhY2snCiAgICAgICAgbWF0Y2hlcnM6CiAgICAgICAgICAtIGFsZXJ0bmFtZSA9fiAiSW5mb0luaGliaXRvcnxXYXRjaGRvZyIKICAgIHJlY2VpdmVyczoKICAgIC0gbmFtZTogJ3NsYWNrJwogICAgdGVtcGxhdGVzOgogICAgLSAnL2V0Yy9hbGVydG1hbmFnZXIvY29uZmlnLyoudG1wbCc=

